name: Build dev binary
on:
  workflow_dispatch:

jobs:
  build-win32:
    name: Build x86 Windows binary
    runs-on: windows-2019
    env:
      BUILD_ARCH: x86
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/setup-python@v3
        with:
          python-version: '2.7'
      - uses: actions/checkout@v3
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 nyuu.7z config-sample.json nexe/nyuu.exe
      - uses: actions/upload-artifact@v3
        with:
          path: ./nyuu.7z
          name: nyuu-${{ steps.get_release.outputs.tag_name }}-win32.7z
          retention-days: 5
  
  build-linux:
    strategy:
      matrix:
        include: 
        - target: x86_64-linux-musl
          arch: x64
          xz_bcj: --x86
          name: amd64
        - target: aarch64-linux-musl
          arch: arm64
          xz_bcj: 
          name: aarch64
    name: Build ${{ matrix.name }} Linux binary
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: actions/checkout@v3
      - uses: Lesmiscore/musl-cross-compilers@v0.5
        id: musl
        with:
          target: ${{ matrix.target }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-cc
          CXX: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-c++
          CC_host: cc
          CXX_host: c++
      - run: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-strip nexe/nyuu
      - run: tar --group=nobody --owner=nobody -cf - -C nexe nyuu ../config-sample.json | xz -9e ${{ matrix.xz_bcj }} --lzma2 > nyuu.txz
      - uses: actions/upload-artifact@v3
        with:
          path: ./nyuu.txz
          name: nyuu-${{ steps.get_release.outputs.tag_name }}-linux-${{ matrix.name }}.tar.xz
          retention-days: 5
